# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)'
    Contents: '**'
    TargetFolder: '$(build.artifactstagingdirectory)'
    OverWrite: true
- task: AzureCLI@2 # Update permission for spn (using azcli)
  displayName: 'Provide the SPN access to keyvault'
  inputs:
    connectionType: 'Azure Resource Manager'
    azureSubscription: 'Microsoft Azure Internal Consumption(bc16117b-02f2-49ce-b61f-9349ea8dee86)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript:    
      Sec_per=$(az keyvault set-policy --name ready20-kv --secret-permissions get list --spn "889bf27a-38c9-4f3c-b5a6-0739c60a0947")
      sleep 10
    enabled: true
- task: AzureKeyVault@1
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption(bc16117b-02f2-49ce-b61f-9349ea8dee86)'
    KeyVaultName: 'ready20-kv'
    SecretsFilter: '*'


- task: AzureImageBuilderTask@1
  inputs:
    imageSource: 'marketplace'
    baseImage: 'OpenLogic:CentOS:7.6:linux'
    packagePath: '$(System.DefaultWorkingDirectory)'
    inlineScript: |
      cd /tmp
      sudo wget https://msreadylabs.blob.core.windows.net/workshop/soelab2.sh
      sudo sh soelab2.sh
    storageAccountName: 'reay2020test'
    imageIdForDistribute: '/subscriptions/bc16117b-02f2-49ce-b61f-9349ea8dee86/resourceGroups/ready20/providers/Microsoft.Compute/images/grkumar-task2-image03'
    managedImageLocation: 'westus'
    ibSubscription: 'Microsoft Azure Internal Consumption(bc16117b-02f2-49ce-b61f-9349ea8dee86)'
    ibAzureResourceGroup: 'ready20'
    ibLocation: 'westus'

- task: AzureCLI@2
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: 'Microsoft Azure Internal Consumption (bc16117b-02f2-49ce-b61f-9349ea8dee86)'
    scriptType: batch
    scriptLocation: inlineScript
    inlineScript: |
     call az --version
     call az vm create --resource-group "ready20" --name myAibGalleryVM --admin-username "$(adminuser)" --location "westus" --image "$(imageUri)" --admin-password "$(adminpw)"

